on:
  - pull_request
  - push

name: Deploy API

jobs:
  check:
    name: DVR API
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v3"

      - uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
          service_account: "my-service-account@my-project.iam.gserviceaccount.com"

      - id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: "api"
          image: "gcr.io/cloudrun/hello"

      - name: "Use output"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
