steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "creature-generator-deploy"
    dir: "/packages/serverless/creature_generator"
    args:
      - gcloud
      - functions
      - deploy
      - creature-generator
      - --region=us-west2
      - --source=.
      - --trigger-http
      - --runtime=python311
      - --allow-unauthenticated
      # - --entry-point generate_creature_route
options:
  logging: CLOUD_LOGGING_ONLY
