// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Balance, BalanceTableId } from "./tables/Balance.sol";
import { Owner, OwnerTableId } from "./tables/Owner.sol";
import { Role, RoleTableId } from "./tables/Role.sol";
import { Match, MatchData, MatchTableId } from "./tables/Match.sol";
import { Identity, IdentityData, IdentityTableId } from "./tables/Identity.sol";
import { PlayerID, PlayerIDTableId } from "./tables/PlayerID.sol";
import { Counter, CounterTableId } from "./tables/Counter.sol";
