// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Role, RoleTableId } from "./tables/Role.sol";
import { Identity, IdentityTableId } from "./tables/Identity.sol";
import { Match, MatchData, MatchTableId } from "./tables/Match.sol";
import { Game, GameData, GameTableId } from "./tables/Game.sol";
import { Counter, CounterTableId } from "./tables/Counter.sol";
