// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Role, RoleTableId } from "./tables/Role.sol";
import { State, StateTableId } from "./tables/State.sol";
import { Size, SizeTableId } from "./tables/Size.sol";
import { Owner, OwnerTableId } from "./tables/Owner.sol";
import { Identity, IdentityData, IdentityTableId } from "./tables/Identity.sol";
import { Match, MatchData, MatchTableId } from "./tables/Match.sol";
import { Game, GameData, GameTableId } from "./tables/Game.sol";
import { Cell, CellTableId } from "./tables/Cell.sol";
import { Space, SpaceData, SpaceTableId } from "./tables/Space.sol";
import { ARWorld, ARWorldData, ARWorldTableId } from "./tables/ARWorld.sol";
import { Counter, CounterTableId } from "./tables/Counter.sol";
