// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { State, StateTableId } from "./tables/State.sol";
import { Size, SizeTableId } from "./tables/Size.sol";
import { Owner, OwnerTableId } from "./tables/Owner.sol";
import { Identity, IdentityData, IdentityTableId } from "./tables/Identity.sol";
import { Space, SpaceTableId } from "./tables/Space.sol";
import { Grid, GridData, GridTableId } from "./tables/Grid.sol";
import { Map, MapData, MapTableId } from "./tables/Map.sol";
import { Counter, CounterTableId } from "./tables/Counter.sol";
