// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { State, StateTableId } from "./tables/State.sol";
import { Identity, IdentityData, IdentityTableId } from "./tables/Identity.sol";
import { Space, SpaceData, SpaceTableId } from "./tables/Space.sol";
import { Grid, GridTableId } from "./tables/Grid.sol";
import { Map, MapTableId } from "./tables/Map.sol";
