// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum RoleEnum {
  O,
  X
}

enum StateEnum {
  Active,
  Frozen
}

enum SizeEnum {
  Mini,
  Small,
  Medium,
  Large
}
