version: "3.9"
services:
  redis:
    container_name: wefa-redis-cache
    image: redis:4.0.8-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    entrypoint: redis-server --appendonly yes
  postgres:
    container_name: wefa-postgres-db
    hostname: postgres
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: openar
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
