// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICellSystem {
  function setCell(bytes32 worldId, bytes32 spaceId, uint32 position, bytes32[] calldata value) external;
}
