// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICellSystem {
  function openar_CellSystem_setCell(
    bytes32 worldId,
    bytes32 spaceId,
    uint32 position,
    uint8 x,
    uint8 y,
    bytes32[] calldata value
  ) external;
}
