// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICellSystem {
  function setCell(bytes32 worldId, bytes32 spaceId, uint32 x, uint32 y, uint32 z, bytes32 value) external;
}
