// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IGameCollectibleSystem {
  function claim(bytes32 matchId) external returns (string memory meta);
}
