// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { StateEnum } from "./../Types.sol";

interface IGridSystem {
  function openar_GridSystem_claimGrid(bytes32 mapId) external returns (bytes32);

  function openar_GridSystem_transferGrid(bytes32 mapId, bytes32 gridId, address to) external returns (bytes32);

  function openar_GridSystem_setGrid(
    bytes32 mapId,
    bytes32 gridId,
    StateEnum state,
    string memory name,
    string memory description,
    string memory image
  ) external returns (bytes32);
}
