// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { SizeEnum } from "./../Types.sol";

interface IMapSystem {
  function openar_MapSystem_createMap(
    string memory name,
    string memory description,
    string memory image,
    SizeEnum size
  ) external returns (bytes32);
}
