// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { StateEnum } from "./../Types.sol";

interface ISpaceSystem {
  function openar_SpaceSystem_claimSpace(bytes32 worldId) external returns (bytes32);

  function openar_SpaceSystem_transferSpace(bytes32 worldId, bytes32 spaceId, address to) external returns (bytes32);

  function openar_SpaceSystem_setSpace(
    bytes32 worldId,
    bytes32 spaceId,
    StateEnum state,
    string memory name,
    string memory description,
    string memory image
  ) external returns (bytes32);
}
