// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ISpaceSystem {
  function openar_SpaceSystem_setSpace(
    bytes32 mapId,
    bytes32 gridId,
    uint8 x,
    uint8 y,
    bytes32[] calldata value
  ) external;
}
