// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/interfaces/IBaseWorld.sol";

import { ICellSystem } from "./ICellSystem.sol";
import { IGameCollectibleSystem } from "./IGameCollectibleSystem.sol";
import { IGameMoveSystem } from "./IGameMoveSystem.sol";
import { IGameStartSystem } from "./IGameStartSystem.sol";
import { IIncrementSystem } from "./IIncrementSystem.sol";
import { ISpaceSystem } from "./ISpaceSystem.sol";
import { IWorldSystem } from "./IWorldSystem.sol";

/**
 * The IWorld interface includes all systems dynamically added to the World
 * during the deploy process.
 */
interface IWorld is
  IBaseWorld,
  ICellSystem,
  IGameCollectibleSystem,
  IGameMoveSystem,
  IGameStartSystem,
  IIncrementSystem,
  ISpaceSystem,
  IWorldSystem
{

}
