// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IGameMoveSystem {
  function checkers_GameMove_movePosition(bytes32 gameId, bytes32 spaceId, uint8 from, uint8 to) external;
}
