// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICollectibleSystem {
  function claim(bytes32 gameId) external returns (uint256);

  function gift(uint256 tokenId, address recipient) external returns (uint256);
}
