// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { RoleEnum } from "./../Types.sol";

interface IGameInitSystem {
  function create(RoleEnum role, string memory name) external returns (bytes32);

  function join(bytes32 gameId) external returns (RoleEnum);
}
