// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IGameMoveSystem {
  function tictactoe_GameMove_claimPosition(bytes32 gameId, uint8 x) external;
}
