// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMintSystem {
  function mint(address to, uint256 token) external returns (uint256);
}
