// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICollectibleSystem {
  function claim(address userAddrs) external returns (bytes32);

  function gift(address userAddrs) external returns (bytes32);
}
