// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICreatureSystem {
  function seedCreature(
    string memory image,
    string memory name,
    bytes32 worldId,
    bytes32 spaceId,
    uint8 cellPosition
  ) external returns (address);
}
