// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { RoleEnum } from "./../Types.sol";

interface IGameStartSystem {
  function createGame(RoleEnum role, string memory name, bytes32 worldId, bytes32 spaceId) external returns (bytes32);

  function joinGame(bytes32 gameId) external returns (RoleEnum);
}
