// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IGameMoveSystem {
  function claimPosition(address userAddrs) external returns (bytes32);
}
