// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IGameInitSystem {
  function create(address userAddrs) external returns (bytes32);

  function join(address userAddrs) external returns (bytes32);
}
