// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { GrowthLevelEnum } from "./../Types.sol";

interface IPlantSystem {
  function redeem(
    string memory image,
    string memory meta,
    int32 long,
    int32 lat,
    GrowthLevelEnum growthLevel,
    address userAddrs
  ) external returns (bytes32);
}
