// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { ActivityEnum, StateEnum } from "./../Types.sol";

interface ISpaceSystem {
  function setSpaceActivity(
    bytes32 worldId,
    bytes32 spaceId,
    ActivityEnum activity,
    address client
  ) external returns (bytes32);

  function setSpace(
    bytes32 worldId,
    bytes32 spaceId,
    StateEnum state,
    string memory name,
    string memory description,
    string memory image
  ) external returns (bytes32);
}
