// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/interfaces/IBaseWorld.sol";

import { ICollectibleSystem } from "./ICollectibleSystem.sol";
import { IGameInitSystem } from "./IGameInitSystem.sol";
import { IGameMoveSystem } from "./IGameMoveSystem.sol";
import { IIncrementSystem } from "./IIncrementSystem.sol";
import { IMintSystem } from "./IMintSystem.sol";
import { ITransferSystem } from "./ITransferSystem.sol";

/**
 * The IWorld interface includes all systems dynamically added to the World
 * during the deploy process.
 */
interface IWorld is
  IBaseWorld,
  ICollectibleSystem,
  IGameInitSystem,
  IGameMoveSystem,
  IIncrementSystem,
  IMintSystem,
  ITransferSystem
{

}
