// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16("openar"), bytes16("Space")));
bytes32 constant SpaceTableId = _tableId;

struct SpaceData {
  uint8 x;
  uint8 y;
  bytes32[] value;
}

library Space {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](3);
    _schema[0] = SchemaType.UINT8;
    _schema[1] = SchemaType.UINT8;
    _schema[2] = SchemaType.BYTES32_ARRAY;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](2);
    _schema[0] = SchemaType.ADDRESS;
    _schema[1] = SchemaType.BYTES32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](3);
    _fieldNames[0] = "x";
    _fieldNames[1] = "y";
    _fieldNames[2] = "value";
    return ("Space", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get x */
  function getX(address owner, bytes32 gridId) internal view returns (uint8 x) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0);
    return (uint8(Bytes.slice1(_blob, 0)));
  }

  /** Get x (using the specified store) */
  function getX(IStore _store, address owner, bytes32 gridId) internal view returns (uint8 x) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0);
    return (uint8(Bytes.slice1(_blob, 0)));
  }

  /** Set x */
  function setX(address owner, bytes32 gridId, uint8 x) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((x)));
  }

  /** Set x (using the specified store) */
  function setX(IStore _store, address owner, bytes32 gridId, uint8 x) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((x)));
  }

  /** Get y */
  function getY(address owner, bytes32 gridId) internal view returns (uint8 y) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1);
    return (uint8(Bytes.slice1(_blob, 0)));
  }

  /** Get y (using the specified store) */
  function getY(IStore _store, address owner, bytes32 gridId) internal view returns (uint8 y) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1);
    return (uint8(Bytes.slice1(_blob, 0)));
  }

  /** Set y */
  function setY(address owner, bytes32 gridId, uint8 y) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    StoreSwitch.setField(_tableId, _keyTuple, 1, abi.encodePacked((y)));
  }

  /** Set y (using the specified store) */
  function setY(IStore _store, address owner, bytes32 gridId, uint8 y) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    _store.setField(_tableId, _keyTuple, 1, abi.encodePacked((y)));
  }

  /** Get value */
  function getValue(address owner, bytes32 gridId) internal view returns (bytes32[] memory value) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 2);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes32());
  }

  /** Get value (using the specified store) */
  function getValue(IStore _store, address owner, bytes32 gridId) internal view returns (bytes32[] memory value) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 2);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes32());
  }

  /** Set value */
  function setValue(address owner, bytes32 gridId, bytes32[] memory value) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    StoreSwitch.setField(_tableId, _keyTuple, 2, EncodeArray.encode((value)));
  }

  /** Set value (using the specified store) */
  function setValue(IStore _store, address owner, bytes32 gridId, bytes32[] memory value) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    _store.setField(_tableId, _keyTuple, 2, EncodeArray.encode((value)));
  }

  /** Get the length of value */
  function lengthValue(address owner, bytes32 gridId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    uint256 _byteLength = StoreSwitch.getFieldLength(_tableId, _keyTuple, 2, getSchema());
    return _byteLength / 32;
  }

  /** Get the length of value (using the specified store) */
  function lengthValue(IStore _store, address owner, bytes32 gridId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    uint256 _byteLength = _store.getFieldLength(_tableId, _keyTuple, 2, getSchema());
    return _byteLength / 32;
  }

  /** Get an item of value (unchecked, returns invalid data if index overflows) */
  function getItemValue(address owner, bytes32 gridId, uint256 _index) internal view returns (bytes32) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    bytes memory _blob = StoreSwitch.getFieldSlice(_tableId, _keyTuple, 2, getSchema(), _index * 32, (_index + 1) * 32);
    return (Bytes.slice32(_blob, 0));
  }

  /** Get an item of value (using the specified store) (unchecked, returns invalid data if index overflows) */
  function getItemValue(IStore _store, address owner, bytes32 gridId, uint256 _index) internal view returns (bytes32) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    bytes memory _blob = _store.getFieldSlice(_tableId, _keyTuple, 2, getSchema(), _index * 32, (_index + 1) * 32);
    return (Bytes.slice32(_blob, 0));
  }

  /** Push an element to value */
  function pushValue(address owner, bytes32 gridId, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    StoreSwitch.pushToField(_tableId, _keyTuple, 2, abi.encodePacked((_element)));
  }

  /** Push an element to value (using the specified store) */
  function pushValue(IStore _store, address owner, bytes32 gridId, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    _store.pushToField(_tableId, _keyTuple, 2, abi.encodePacked((_element)));
  }

  /** Pop an element from value */
  function popValue(address owner, bytes32 gridId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    StoreSwitch.popFromField(_tableId, _keyTuple, 2, 32);
  }

  /** Pop an element from value (using the specified store) */
  function popValue(IStore _store, address owner, bytes32 gridId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    _store.popFromField(_tableId, _keyTuple, 2, 32);
  }

  /** Update an element of value at `_index` */
  function updateValue(address owner, bytes32 gridId, uint256 _index, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    StoreSwitch.updateInField(_tableId, _keyTuple, 2, _index * 32, abi.encodePacked((_element)));
  }

  /** Update an element of value (using the specified store) at `_index` */
  function updateValue(IStore _store, address owner, bytes32 gridId, uint256 _index, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    _store.updateInField(_tableId, _keyTuple, 2, _index * 32, abi.encodePacked((_element)));
  }

  /** Get the full data */
  function get(address owner, bytes32 gridId) internal view returns (SpaceData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(IStore _store, address owner, bytes32 gridId) internal view returns (SpaceData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(address owner, bytes32 gridId, uint8 x, uint8 y, bytes32[] memory value) internal {
    bytes memory _data = encode(x, y, value);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(IStore _store, address owner, bytes32 gridId, uint8 x, uint8 y, bytes32[] memory value) internal {
    bytes memory _data = encode(x, y, value);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    _store.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using the data struct */
  function set(address owner, bytes32 gridId, SpaceData memory _table) internal {
    set(owner, gridId, _table.x, _table.y, _table.value);
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, address owner, bytes32 gridId, SpaceData memory _table) internal {
    set(_store, owner, gridId, _table.x, _table.y, _table.value);
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal view returns (SpaceData memory _table) {
    // 2 is the total byte length of static data
    PackedCounter _encodedLengths = PackedCounter.wrap(Bytes.slice32(_blob, 2));

    _table.x = (uint8(Bytes.slice1(_blob, 0)));

    _table.y = (uint8(Bytes.slice1(_blob, 1)));

    // Store trims the blob if dynamic fields are all empty
    if (_blob.length > 2) {
      uint256 _start;
      // skip static data length + dynamic lengths word
      uint256 _end = 34;

      _start = _end;
      _end += _encodedLengths.atIndex(0);
      _table.value = (SliceLib.getSubslice(_blob, _start, _end).decodeArray_bytes32());
    }
  }

  /** Tightly pack full data using this table's schema */
  function encode(uint8 x, uint8 y, bytes32[] memory value) internal view returns (bytes memory) {
    uint40[] memory _counters = new uint40[](1);
    _counters[0] = uint40(value.length * 32);
    PackedCounter _encodedLengths = PackedCounterLib.pack(_counters);

    return abi.encodePacked(x, y, _encodedLengths.unwrap(), EncodeArray.encode((value)));
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(address owner, bytes32 gridId) internal pure returns (bytes32[] memory _keyTuple) {
    _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));
  }

  /* Delete all data for given keys */
  function deleteRecord(address owner, bytes32 gridId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, address owner, bytes32 gridId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((owner))));
    _keyTuple[1] = bytes32((gridId));

    _store.deleteRecord(_tableId, _keyTuple);
  }
}
