// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IGridSystem {
  function openar_GridSystem_claimGrid(string memory name) external returns (bytes32);

  function openar_GridSystem_transferGrid(bytes32 gameId) external returns (bytes32);
}
