// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ISpaceSystem {
  function openar_SpaceSystem_setSpace(bytes32 gameId, uint8 x) external;
}
