/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Role: (() => {
      const tableId = new TableId("tictactoe", "Role");
      return defineComponent(
        world,
        {
          value: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Identity: (() => {
      const tableId = new TableId("tictactoe", "Identity");
      return defineComponent(
        world,
        {
          createdAt: RecsType.BigInt,
          name: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Match: (() => {
      const tableId = new TableId("tictactoe", "Match");
      return defineComponent(
        world,
        {
          turnCount: RecsType.Number,
          id: RecsType.String,
          gridId: RecsType.String,
          gridPosition: RecsType.Number,
          currentPlayer: RecsType.String,
          winner: RecsType.String,
          players: RecsType.StringArray,
          board: RecsType.NumberArray,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Game: (() => {
      const tableId = new TableId("tictactoe", "Game");
      return defineComponent(
        world,
        {
          matches: RecsType.StringArray,
          winner: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Counter: (() => {
      const tableId = new TableId("tictactoe", "Counter");
      return defineComponent(
        world,
        {
          value: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
