[profile.default]
solc_version = "0.8.13"
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 3000
verbosity = 1
src = "src"
test = "test"
out = "out"
allow_paths = ["../../node_modules", "../../../packages"] # TODO May cause issues
extra_output_files = [
  "abi",
  "evm.bytecode"
]
fs_permissions = [{ access = "read", path = "./"}]

[profile.lattice-testnet]
eth_rpc_url = "https://follower.testnet-chain.linfra.xyz"

[profile.optimism-goerli]
eth_rpc_url = "https://opt-goerli.g.alchemy.com/v2/UF7j76yPWLAbLszYLS50UzHQYg3K3m9X"

[profile.optimism]
eth_rpc_url = "https://opt-mainnet.g.alchemy.com/v2/AJMG7qpBNCskviWEj93HW4nioGl8neDp"
