// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16("tictactoe"), bytes16("Match")));
bytes32 constant MatchTableId = _tableId;

struct MatchData {
  bytes32 currentPlayer;
  uint8 turnCount;
  address winner;
  uint8[9] board;
}

library Match {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](4);
    _schema[0] = SchemaType.BYTES32;
    _schema[1] = SchemaType.UINT8;
    _schema[2] = SchemaType.ADDRESS;
    _schema[3] = SchemaType.UINT8_ARRAY;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](2);
    _schema[0] = SchemaType.BYTES32;
    _schema[1] = SchemaType.BYTES32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](4);
    _fieldNames[0] = "currentPlayer";
    _fieldNames[1] = "turnCount";
    _fieldNames[2] = "winner";
    _fieldNames[3] = "board";
    return ("Match", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get currentPlayer */
  function getCurrentPlayer(bytes32 id, bytes32 gridId) internal view returns (bytes32 currentPlayer) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0);
    return (Bytes.slice32(_blob, 0));
  }

  /** Get currentPlayer (using the specified store) */
  function getCurrentPlayer(IStore _store, bytes32 id, bytes32 gridId) internal view returns (bytes32 currentPlayer) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0);
    return (Bytes.slice32(_blob, 0));
  }

  /** Set currentPlayer */
  function setCurrentPlayer(bytes32 id, bytes32 gridId, bytes32 currentPlayer) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((currentPlayer)));
  }

  /** Set currentPlayer (using the specified store) */
  function setCurrentPlayer(IStore _store, bytes32 id, bytes32 gridId, bytes32 currentPlayer) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((currentPlayer)));
  }

  /** Get turnCount */
  function getTurnCount(bytes32 id, bytes32 gridId) internal view returns (uint8 turnCount) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1);
    return (uint8(Bytes.slice1(_blob, 0)));
  }

  /** Get turnCount (using the specified store) */
  function getTurnCount(IStore _store, bytes32 id, bytes32 gridId) internal view returns (uint8 turnCount) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1);
    return (uint8(Bytes.slice1(_blob, 0)));
  }

  /** Set turnCount */
  function setTurnCount(bytes32 id, bytes32 gridId, uint8 turnCount) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    StoreSwitch.setField(_tableId, _keyTuple, 1, abi.encodePacked((turnCount)));
  }

  /** Set turnCount (using the specified store) */
  function setTurnCount(IStore _store, bytes32 id, bytes32 gridId, uint8 turnCount) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    _store.setField(_tableId, _keyTuple, 1, abi.encodePacked((turnCount)));
  }

  /** Get winner */
  function getWinner(bytes32 id, bytes32 gridId) internal view returns (address winner) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 2);
    return (address(Bytes.slice20(_blob, 0)));
  }

  /** Get winner (using the specified store) */
  function getWinner(IStore _store, bytes32 id, bytes32 gridId) internal view returns (address winner) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 2);
    return (address(Bytes.slice20(_blob, 0)));
  }

  /** Set winner */
  function setWinner(bytes32 id, bytes32 gridId, address winner) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    StoreSwitch.setField(_tableId, _keyTuple, 2, abi.encodePacked((winner)));
  }

  /** Set winner (using the specified store) */
  function setWinner(IStore _store, bytes32 id, bytes32 gridId, address winner) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    _store.setField(_tableId, _keyTuple, 2, abi.encodePacked((winner)));
  }

  /** Get board */
  function getBoard(bytes32 id, bytes32 gridId) internal view returns (uint8[9] memory board) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 3);
    return toStaticArray_uint8_9(SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_uint8());
  }

  /** Get board (using the specified store) */
  function getBoard(IStore _store, bytes32 id, bytes32 gridId) internal view returns (uint8[9] memory board) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 3);
    return toStaticArray_uint8_9(SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_uint8());
  }

  /** Set board */
  function setBoard(bytes32 id, bytes32 gridId, uint8[9] memory board) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    StoreSwitch.setField(_tableId, _keyTuple, 3, EncodeArray.encode(fromStaticArray_uint8_9(board)));
  }

  /** Set board (using the specified store) */
  function setBoard(IStore _store, bytes32 id, bytes32 gridId, uint8[9] memory board) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    _store.setField(_tableId, _keyTuple, 3, EncodeArray.encode(fromStaticArray_uint8_9(board)));
  }

  /** Get the length of board */
  function lengthBoard(bytes32 id, bytes32 gridId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    uint256 _byteLength = StoreSwitch.getFieldLength(_tableId, _keyTuple, 3, getSchema());
    return _byteLength / 1;
  }

  /** Get the length of board (using the specified store) */
  function lengthBoard(IStore _store, bytes32 id, bytes32 gridId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    uint256 _byteLength = _store.getFieldLength(_tableId, _keyTuple, 3, getSchema());
    return _byteLength / 1;
  }

  /** Get an item of board (unchecked, returns invalid data if index overflows) */
  function getItemBoard(bytes32 id, bytes32 gridId, uint256 _index) internal view returns (uint8) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    bytes memory _blob = StoreSwitch.getFieldSlice(_tableId, _keyTuple, 3, getSchema(), _index * 1, (_index + 1) * 1);
    return (uint8(Bytes.slice1(_blob, 0)));
  }

  /** Get an item of board (using the specified store) (unchecked, returns invalid data if index overflows) */
  function getItemBoard(IStore _store, bytes32 id, bytes32 gridId, uint256 _index) internal view returns (uint8) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    bytes memory _blob = _store.getFieldSlice(_tableId, _keyTuple, 3, getSchema(), _index * 1, (_index + 1) * 1);
    return (uint8(Bytes.slice1(_blob, 0)));
  }

  /** Push an element to board */
  function pushBoard(bytes32 id, bytes32 gridId, uint8 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    StoreSwitch.pushToField(_tableId, _keyTuple, 3, abi.encodePacked((_element)));
  }

  /** Push an element to board (using the specified store) */
  function pushBoard(IStore _store, bytes32 id, bytes32 gridId, uint8 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    _store.pushToField(_tableId, _keyTuple, 3, abi.encodePacked((_element)));
  }

  /** Pop an element from board */
  function popBoard(bytes32 id, bytes32 gridId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    StoreSwitch.popFromField(_tableId, _keyTuple, 3, 1);
  }

  /** Pop an element from board (using the specified store) */
  function popBoard(IStore _store, bytes32 id, bytes32 gridId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    _store.popFromField(_tableId, _keyTuple, 3, 1);
  }

  /** Update an element of board at `_index` */
  function updateBoard(bytes32 id, bytes32 gridId, uint256 _index, uint8 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    StoreSwitch.updateInField(_tableId, _keyTuple, 3, _index * 1, abi.encodePacked((_element)));
  }

  /** Update an element of board (using the specified store) at `_index` */
  function updateBoard(IStore _store, bytes32 id, bytes32 gridId, uint256 _index, uint8 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    _store.updateInField(_tableId, _keyTuple, 3, _index * 1, abi.encodePacked((_element)));
  }

  /** Get the full data */
  function get(bytes32 id, bytes32 gridId) internal view returns (MatchData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(IStore _store, bytes32 id, bytes32 gridId) internal view returns (MatchData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(
    bytes32 id,
    bytes32 gridId,
    bytes32 currentPlayer,
    uint8 turnCount,
    address winner,
    uint8[9] memory board
  ) internal {
    bytes memory _data = encode(currentPlayer, turnCount, winner, board);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(
    IStore _store,
    bytes32 id,
    bytes32 gridId,
    bytes32 currentPlayer,
    uint8 turnCount,
    address winner,
    uint8[9] memory board
  ) internal {
    bytes memory _data = encode(currentPlayer, turnCount, winner, board);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    _store.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using the data struct */
  function set(bytes32 id, bytes32 gridId, MatchData memory _table) internal {
    set(id, gridId, _table.currentPlayer, _table.turnCount, _table.winner, _table.board);
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, bytes32 id, bytes32 gridId, MatchData memory _table) internal {
    set(_store, id, gridId, _table.currentPlayer, _table.turnCount, _table.winner, _table.board);
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal view returns (MatchData memory _table) {
    // 53 is the total byte length of static data
    PackedCounter _encodedLengths = PackedCounter.wrap(Bytes.slice32(_blob, 53));

    _table.currentPlayer = (Bytes.slice32(_blob, 0));

    _table.turnCount = (uint8(Bytes.slice1(_blob, 32)));

    _table.winner = (address(Bytes.slice20(_blob, 33)));

    // Store trims the blob if dynamic fields are all empty
    if (_blob.length > 53) {
      uint256 _start;
      // skip static data length + dynamic lengths word
      uint256 _end = 85;

      _start = _end;
      _end += _encodedLengths.atIndex(0);
      _table.board = toStaticArray_uint8_9(SliceLib.getSubslice(_blob, _start, _end).decodeArray_uint8());
    }
  }

  /** Tightly pack full data using this table's schema */
  function encode(
    bytes32 currentPlayer,
    uint8 turnCount,
    address winner,
    uint8[9] memory board
  ) internal view returns (bytes memory) {
    uint40[] memory _counters = new uint40[](1);
    _counters[0] = uint40(board.length * 1);
    PackedCounter _encodedLengths = PackedCounterLib.pack(_counters);

    return
      abi.encodePacked(
        currentPlayer,
        turnCount,
        winner,
        _encodedLengths.unwrap(),
        EncodeArray.encode(fromStaticArray_uint8_9(board))
      );
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(bytes32 id, bytes32 gridId) internal pure returns (bytes32[] memory _keyTuple) {
    _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));
  }

  /* Delete all data for given keys */
  function deleteRecord(bytes32 id, bytes32 gridId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, bytes32 id, bytes32 gridId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32((id));
    _keyTuple[1] = bytes32((gridId));

    _store.deleteRecord(_tableId, _keyTuple);
  }
}

function toStaticArray_uint8_9(uint8[] memory _value) pure returns (uint8[9] memory _result) {
  // in memory static arrays are just dynamic arrays without the length byte
  assembly {
    _result := add(_value, 0x20)
  }
}

function fromStaticArray_uint8_9(uint8[9] memory _value) view returns (uint8[] memory _result) {
  _result = new uint8[](9);
  uint256 fromPointer;
  uint256 toPointer;
  assembly {
    fromPointer := _value
    toPointer := add(_result, 0x20)
  }
  Memory.copy(fromPointer, toPointer, 288);
}
